[workspace]
members = [
    "checksum",
    "crate_tool",
    "google_metadata",
    "license_checker",
    "name_and_version",
    "name_and_version_proc_macros",
    "rooted_path",
    "test_mapping",
]
resolver = "2"
